import type { Metadata } from "next";
import { Kanit } from 'next/font/google';
import "./globals.css";

//Nunito_Sans otra tipografia no utilizada todavia
const kanit = Kanit({
  subsets: ['latin'],
  weight: '400'
});
//const nunitoSans = Nunito_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.className}`}>
        {children}
      </body>
    </html>
  );
}
