import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import { ContactInfoProvider } from "@/lib/ContactInforContext";

// Fuente Kanit
const kanit = Kanit({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "ACAVISA",
  description: "Generated by create next app",
  icons: {
    icon: "/logos/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon/favicon.png" type="image/png" sizes="90" />
        <link rel="icon" href="/logos/favicon.png" type="image/png" />
      </head>
      <body className={`${kanit.className}`}>
        <ContactInfoProvider>{children}</ContactInfoProvider>
      </body>
    </html>
  );
}
